"use client";

import { useEffect, useState, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { api, Study, Brief } from "../lib/api";

function BriefContent() {
  const params     = useSearchParams();
  const preStudyId = params.get("study") ?? "";

  const [allStudies, setAllStudies] = useState<Study[]>([]);
  const [selectedId, setSelectedId] = useState(preStudyId);
  const [study, setStudy]           = useState<Study | null>(null);
  const [brief, setBrief]           = useState<Brief | null>(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError]           = useState("");
  const [search, setSearch]         = useState("");

  // Load study list for selector
  useEffect(() => {
    api.search({ domain: "labour", query: "", sort_order: "Newest first", use_ai: false })
      .then((r) => setAllStudies(r.results))
      .catch(() => {});
  }, []);

  // Load study detail when selection changes
  useEffect(() => {
    if (!selectedId) return;
    api.study(selectedId)
      .then((s) => { setStudy(s); setBrief(null); setError(""); })
      .catch(() => setStudy(null));
  }, [selectedId]);

  async function generate() {
    if (!selectedId) return;
    setGenerating(true);
    setError("");
    setBrief(null);
    try {
      const r = await api.brief(selectedId);
      setBrief(r.brief);
      setStudy(r.study);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Brief generation failed.");
    } finally {
      setGenerating(false);
    }
  }

  function downloadTxt() {
    if (!brief || !study) return;
    const text = `ADVOCACY BRIEF
${"=".repeat(60)}
${study.title} (${study.year})
${study.organization}

POLICY CONTEXT
${brief.policy_context}

KEY FINDINGS
${brief.key_findings}

DATA GAPS
${brief.data_gaps}

RECOMMENDED ACTION
${brief.recommended_action}

CITATION
${brief.citation}
${"=".repeat(60)}
Generated by Shakisha — AI-Powered Gender Data Discovery Platform
GDRD Hackathon 2026
`;
    const blob = new Blob([text], { type: "text/plain" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href = url;
    a.download = `shakisha_brief_${study.study_id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const QUALITY_BADGE = {
    good:     { cls: "badge-good",     label: "Good quality" },
    warning:  { cls: "badge-warning",  label: "Some missing fields" },
    critical: { cls: "badge-critical", label: "Missing critical fields" },
  };

  // Filter studies for selector search
  const filteredStudies = allStudies.filter((s) =>
    !search || s.title.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div style={{ background: "var(--cream)", minHeight: "100vh" }}>
      <div className="page-wrap" style={{ maxWidth: 900 }}>
        <h1 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 32, fontWeight: 700, color: "var(--charcoal)", marginBottom: 8 }}>
          Advocacy Brief Generator
        </h1>
        <p style={{ color: "var(--muted)", fontSize: 14, marginBottom: 28 }}>
          Select a study and generate an AI-powered policy brief ready for advocacy use.
        </p>

        {/* Study selector */}
        <div style={{ background: "var(--warm-white)", border: "1px solid var(--border)", borderRadius: 12, padding: "24px", marginBottom: 24 }}>
          <div style={{ fontWeight: 700, fontSize: 15, color: "var(--charcoal)", marginBottom: 12 }}>
            Choose a study
          </div>
          <input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search study title…"
            style={{ width: "100%", padding: "8px 14px", borderRadius: 8, border: "1.5px solid var(--border)", background: "var(--cream)", fontSize: 13, marginBottom: 10, boxSizing: "border-box" }}
          />
          <select
            value={selectedId}
            onChange={(e) => setSelectedId(e.target.value)}
            size={6}
            style={{
              width: "100%",
              border: "1.5px solid var(--border)",
              borderRadius: 8,
              background: "var(--cream)",
              fontSize: 13,
              color: "var(--charcoal)",
              padding: "4px",
            }}
          >
            {filteredStudies.map((s) => (
              <option key={s.study_id} value={s.study_id}>
                {s.year ? `[${s.year}] ` : ""}{s.title}
              </option>
            ))}
          </select>
        </div>

        {/* Study metadata panel */}
        {study && (
          <div style={{ background: "var(--warm-white)", border: "1px solid var(--border)", borderRadius: 12, padding: "24px", marginBottom: 24 }}>
            <div className="study-meta-row">
              <div style={{ flex: 1 }}>
                <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 22, fontWeight: 700, color: "var(--charcoal)", marginBottom: 6 }}>
                  {study.title}
                </h2>
                <p style={{ color: "var(--muted)", fontSize: 13, marginBottom: 12 }}>
                  {[study.organization, study.year, study.geographic_coverage].filter(Boolean).join(" · ")}
                </p>
                {study.abstract && (
                  <p style={{ color: "var(--muted)", fontSize: 13, lineHeight: 1.6 }}>
                    {study.abstract.slice(0, 450)}{study.abstract.length > 450 ? "…" : ""}
                  </p>
                )}
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 10, minWidth: 150, alignItems: "flex-end" }}>
                <span className={`pill ${QUALITY_BADGE[study.quality_level]?.cls ?? "badge-warning"}`}>
                  {QUALITY_BADGE[study.quality_level]?.label ?? "Unknown"}
                </span>
                <span style={{ fontSize: 12, color: "var(--muted)" }}>{study.missing_field_count} missing fields</span>
                <span style={{ fontSize: 12, color: "var(--muted)" }}>{study.resource_count} resources</span>
                {study.url && (
                  <a href={study.url} target="_blank" rel="noopener noreferrer" className="btn-icon" style={{ fontSize: 12 }}>
                    View source ↗
                  </a>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Quality warning */}
        {study?.quality_level === "critical" && (
          <div style={{ background: "#FCE8E8", border: "1px solid #E8A0A0", borderRadius: 8, padding: "12px 16px", fontSize: 13, color: "var(--coral-dark)", marginBottom: 20 }}>
            <strong>Data quality warning:</strong> This study has critical missing fields. Review all caveats carefully before citing in advocacy materials.
          </div>
        )}

        {/* Generate button */}
        <div style={{ marginBottom: 28 }}>
          <button
            className="btn-primary"
            style={{ fontSize: 16, padding: "14px 32px" }}
            disabled={!selectedId || generating}
            onClick={generate}
          >
            {generating ? "Generating brief…" : "Generate Advocacy Brief"}
          </button>
          {generating && (
            <p style={{ color: "var(--muted)", fontSize: 13, marginTop: 8 }}>
              Calling Claude AI — usually takes 5–15 seconds…
            </p>
          )}
          {error && (
            <p style={{ color: "var(--coral)", fontSize: 13, marginTop: 8 }}>
              {error}
            </p>
          )}
        </div>

        {/* Brief output */}
        {brief && study && (
          <div className="animate-fade-in">
            <div
              style={{
                background: "var(--warm-white)",
                border: "1px solid var(--border)",
                borderLeft: "4px solid var(--coral)",
                borderRadius: 12,
                marginBottom: 20,
              }}
            >
              <div className="brief-card-pad">
              <div className="brief-header-row">
                <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 24, fontWeight: 700, color: "var(--charcoal)" }}>
                  Advocacy Brief
                </h2>
                <button className="btn-primary" onClick={downloadTxt} style={{ fontSize: 13 }}>
                  Download .txt ↓
                </button>
              </div>

              <div className="grid-2col" style={{ gap: 28 }}>
                <div>
                  <h3 style={{ fontWeight: 700, fontSize: 14, color: "var(--coral)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10 }}>
                    Policy Context
                  </h3>
                  <p style={{ color: "var(--charcoal)", fontSize: 14, lineHeight: 1.7 }}>
                    {brief.policy_context}
                  </p>
                </div>

                <div>
                  <h3 style={{ fontWeight: 700, fontSize: 14, color: "var(--coral)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10 }}>
                    Data Gaps
                  </h3>
                  <p style={{ color: "var(--charcoal)", fontSize: 14, lineHeight: 1.7 }}>
                    {brief.data_gaps}
                  </p>
                </div>
              </div>

              <div style={{ marginTop: 24 }}>
                <h3 style={{ fontWeight: 700, fontSize: 14, color: "var(--coral)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10 }}>
                  Key Findings
                </h3>
                <div style={{ color: "var(--charcoal)", fontSize: 14, lineHeight: 2 }}>
                  {brief.key_findings.split("\n").filter(Boolean).map((line, i) => (
                    <div key={i} style={{ display: "flex", gap: 10, marginBottom: 4 }}>
                      <span style={{ color: "var(--coral)", fontWeight: 700, flexShrink: 0 }}>•</span>
                      <span>{line.replace(/^[•\-]\s*/, "")}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div
                style={{
                  marginTop: 24,
                  background: "rgba(32,96,61,0.07)",
                  border: "1px solid var(--rw-green-light)",
                  borderRadius: 8,
                  padding: "16px 20px",
                }}
              >
                <h3 style={{ fontWeight: 700, fontSize: 14, color: "var(--rw-green)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 }}>
                  Recommended Action
                </h3>
                <p style={{ color: "var(--charcoal)", fontSize: 14, lineHeight: 1.7 }}>
                  {brief.recommended_action}
                </p>
              </div>

              <div style={{ marginTop: 24 }}>
                <h3 style={{ fontWeight: 700, fontSize: 14, color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 }}>
                  Citation
                </h3>
                <div className="citation-block">{brief.citation}</div>
              </div>

              {/* Quality caveat in brief */}
              {study.quality_level !== "good" && (
                <div style={{ marginTop: 20, background: "#FEF3B0", border: "1px solid var(--rw-yellow)", borderRadius: 8, padding: "12px 16px", fontSize: 12, color: "#92620A" }}>
                  <strong>Quality note:</strong> This study has {study.missing_field_count} missing metadata field{study.missing_field_count !== 1 ? "s" : ""}. Cross-check cited figures with the original source before formal advocacy use.
                </div>
              )}
              </div>{/* end brief-card-pad */}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default function BriefPage() {
  return (
    <Suspense fallback={<div style={{ padding: 48, color: "var(--muted)" }}>Loading…</div>}>
      <BriefContent />
    </Suspense>
  );
}
