"use client";

import { useEffect, useState, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { api, Study, Brief } from "../lib/api";
import jsPDF from "jspdf";

function BriefContent() {
  const params     = useSearchParams();
  const preStudyId = params.get("study") ?? "";

  const [allStudies, setAllStudies] = useState<Study[]>([]);
  const [selectedId, setSelectedId] = useState(preStudyId);
  const [study, setStudy]           = useState<Study | null>(null);
  const [brief, setBrief]           = useState<Brief | null>(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError]           = useState("");
  const [search, setSearch]         = useState("");
  const [copied, setCopied]         = useState(false);

  // Load study list for selector
  useEffect(() => {
    api.search({ domain: "labour", query: "", sort_order: "Newest first", use_ai: false })
      .then((r) => setAllStudies(r.results))
      .catch(() => {});
  }, []);

  // Load study detail when selection changes
  useEffect(() => {
    if (!selectedId) return;
    api.study(selectedId)
      .then((s) => { setStudy(s); setBrief(null); setError(""); })
      .catch(() => setStudy(null));
  }, [selectedId]);

  async function generate() {
    if (!selectedId) return;
    setGenerating(true);
    setError("");
    setBrief(null);
    try {
      const r = await api.brief(selectedId);
      setBrief(r.brief);
      setStudy(r.study);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Brief generation failed.");
    } finally {
      setGenerating(false);
    }
  }

  function briefText() {
    if (!brief || !study) return "";
    return `ADVOCACY BRIEF
${"=".repeat(60)}
${study.title} (${study.year ?? "—"})
${study.organization ?? ""}

POLICY CONTEXT
${brief.policy_context}

KEY FINDINGS
${brief.key_findings}

DATA GAPS
${brief.data_gaps}

RECOMMENDED ACTION
${brief.recommended_action}

CITATION
${brief.citation}
${"=".repeat(60)}
Generated by Shakisha — AI-Powered Gender Data Discovery Platform
GDRD Hackathon 2026 · Republic of Rwanda
`;
  }

  function copyToClipboard() {
    const text = briefText();
    if (!text) return;
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  }

  async function downloadPdf() {
    if (!brief || !study) return;
    const doc    = new jsPDF({ unit: "mm", format: "a4" });
    const pageW  = doc.internal.pageSize.getWidth();
    const pageH  = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxW   = pageW - margin * 2;
    const FOOTER_H = 16; // reserved at bottom of every page
    const safeH    = pageH - margin - FOOTER_H;

    // Normalize text: em-dashes → hyphen, newlines → space, multi-space → single space.
    // Newline normalization prevents words merging when AI output uses \n mid-sentence.
    const clean = (s: string) =>
      s.replace(/\u2014/g, "-")
       .replace(/\u2013/g, "-")
       .replace(/[\r\n]+/g, " ")
       .replace(/\s{2,}/g, " ")
       .trim();

    // ── Header: Rwanda national symbols image (correct aspect ratio) ─────
    let imgDataUrl = "";
    let imgRenderedH = 0;
    try {
      // Step 1: get base64 data
      const blob   = await fetch("/Government_of_Rwanda_National_Symbols.png").then(r => r.blob());
      imgDataUrl   = await new Promise<string>((res) => {
        const reader = new FileReader();
        reader.onload = () => res(reader.result as string);
        reader.readAsDataURL(blob);
      });
      // Step 2: measure natural dimensions via HTMLImageElement
      const imgEl  = new window.Image();
      imgEl.src    = imgDataUrl;
      await new Promise<void>((res) => { imgEl.onload = () => res(); imgEl.onerror = () => res(); });
      const aspectRatio  = imgEl.naturalWidth > 0 ? imgEl.naturalWidth / imgEl.naturalHeight : 2.5;
      const imgW         = 30;
      imgRenderedH       = imgW / aspectRatio;
      // Centre horizontally, add comfortable top padding
      doc.addImage(imgDataUrl, "PNG", (pageW - imgW) / 2, margin, imgW, imgRenderedH);
    } catch {
      // Image unavailable — carry on without it
    }

    let y = margin + imgRenderedH + (imgRenderedH > 0 ? 10 : 0);

    // ── "ADVOCACY BRIEF" title ────────────────────────────────────────────
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(26, 26, 26);
    doc.text("ADVOCACY BRIEF", pageW / 2, y, { align: "center" });
    y += 8;

    doc.setDrawColor(192, 79, 79);
    doc.setLineWidth(0.7);
    doc.line(margin, y, pageW - margin, y);
    y += 7;

    // ── Study title ───────────────────────────────────────────────────────
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(26, 26, 26);
    const titleLines = doc.splitTextToSize(clean(study.title), maxW);
    doc.text(titleLines, margin, y);
    y += titleLines.length * 6 + 3;

    // ── Org / year / coverage — wrapped so it never overflows ─────────────
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(138, 106, 90);
    const orgText  = [study.organization, study.year, study.geographic_coverage]
      .filter(Boolean).join("  |  ");
    const orgLines = doc.splitTextToSize(clean(orgText), maxW);
    doc.text(orgLines, margin, y);
    y += orgLines.length * 5 + 8;

    // ── Section helper — page-break aware ────────────────────────────────
    const LINE_H    = 6.5;
    const HEADING_H = 9;

    // Manual word-spacing justification — avoids jsPDF align:"justify" y-tracking bugs.
    // Skips justification for: last line, single-word lines, lines shorter than 60% of
    // the container (would create huge gaps), or lines where gap > 3 mm (looks broken).
    function writeJustified(lines: string[], startX: number, width: number, isLastLine: (i: number) => boolean) {
      lines.forEach((line: string, idx: number) => {
        if (y + LINE_H > safeH) { doc.addPage(); y = margin; }
        const words = line.trim().split(/\s+/);
        const lineW  = doc.getTextWidth(line.trim());
        const tooShort = lineW < width * 0.6;
        if (isLastLine(idx) || words.length <= 1 || tooShort) {
          doc.text(line, startX, y);
        } else {
          const totalTextW = words.reduce((sum, w) => sum + doc.getTextWidth(w), 0);
          const gap = (width - totalTextW) / (words.length - 1);
          if (gap > 3) {
            // Gap too wide — fall back to left-align to avoid broken look
            doc.text(line, startX, y);
          } else {
            let cx = startX;
            words.forEach((word) => {
              doc.text(word, cx, y);
              cx += doc.getTextWidth(word) + gap;
            });
          }
        }
        y += LINE_H;
      });
    }

    function renderSectionHeading(heading: string, headingColor: [number, number, number]) {
      if (y + HEADING_H + LINE_H > safeH) { doc.addPage(); y = margin; }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...headingColor);
      doc.text(heading.toUpperCase(), margin, y);
      y += HEADING_H - 2;
    }

    // Justified paragraph section
    function addSection(heading: string, body: string, headingColor: [number, number, number] = [192, 79, 79]) {
      renderSectionHeading(heading, headingColor);
      const bodyLines = doc.splitTextToSize(clean(body), maxW);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(26, 26, 26);
      writeJustified(bodyLines, margin, maxW, (i) => i === bodyLines.length - 1);
      y += 8;
    }

    // Bullet-point section — always left-aligned, bullet symbol separate from text
    function addBulletSection(heading: string, body: string, headingColor: [number, number, number] = [192, 79, 79]) {
      renderSectionHeading(heading, headingColor);
      const BULLET_X    = margin;
      const TEXT_X      = margin + 5;
      const BULLET_W    = maxW - 5;
      // Split on newlines BEFORE clean() so we keep bullet boundaries
      const rawBullets = body.split(/\n/).map(l => l.trim()).filter(Boolean);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(26, 26, 26);
      rawBullets.forEach((raw) => {
        // Strip bullet symbols, then clean the text
        const text  = raw.replace(/^[•\-*]\s*/, "").replace(/\u2014/g, "-").replace(/\u2013/g, "-").replace(/\s{2,}/g, " ").trim();
        const lines = doc.splitTextToSize(text, BULLET_W);
        lines.forEach((line: string, i: number) => {
          if (y + LINE_H > safeH) { doc.addPage(); y = margin; }
          if (i === 0) doc.text("•", BULLET_X, y);
          doc.text(line, TEXT_X, y);
          y += LINE_H;
        });
        y += 1.5; // small gap between bullets
      });
      y += 6;
    }

    addSection("Policy Context",     brief.policy_context);
    addBulletSection("Key Findings", brief.key_findings);
    addSection("Data Gaps",          brief.data_gaps);
    addSection("Recommended Action", brief.recommended_action, [32, 96, 61]);

    // ── Citation box — measure height BEFORE drawing so border fits ───────
    const CIT_INDENT  = 4;
    const CIT_TEXT_W  = maxW - CIT_INDENT * 2;
    const CIT_PAD_TOP = 5;   // space above "CITATION" label inside box
    const CIT_LABEL_H = 6;   // "CITATION" label baseline offset from top
    const CIT_GAP     = 4;   // gap between label and first text line
    const CIT_PAD_BOT = 5;   // space below last text line

    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    const citLines = doc.splitTextToSize(clean(brief.citation), CIT_TEXT_W);
    const boxH     = CIT_PAD_TOP + CIT_LABEL_H + CIT_GAP + citLines.length * 5.2 + CIT_PAD_BOT;

    // Move to new page if the whole box won't fit
    if (y + boxH > safeH) { doc.addPage(); y = margin; }

    doc.setFillColor(240, 232, 220);
    doc.roundedRect(margin, y, maxW, boxH, 2, 2, "F");

    // "CITATION" label
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(138, 106, 90);
    doc.text("CITATION", margin + CIT_INDENT, y + CIT_PAD_TOP + CIT_LABEL_H);

    // Citation text lines — manually justified
    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    doc.setTextColor(40, 20, 10);
    const citTextStartY = y + CIT_PAD_TOP + CIT_LABEL_H + CIT_GAP;
    citLines.forEach((line: string, i: number) => {
      const lineY = citTextStartY + (i + 1) * 5.2;
      const isLast = i === citLines.length - 1;
      if (isLast) {
        doc.text(line, margin + CIT_INDENT, lineY);
      } else {
        const words = line.trim().split(/\s+/);
        if (words.length <= 1) {
          doc.text(line, margin + CIT_INDENT, lineY);
        } else {
          const totalTextW = words.reduce((sum, w) => sum + doc.getTextWidth(w), 0);
          const gap = (CIT_TEXT_W - totalTextW) / (words.length - 1);
          let cx = margin + CIT_INDENT;
          words.forEach((word) => {
            doc.text(word, cx, lineY);
            cx += doc.getTextWidth(word) + gap;
          });
        }
      }
    });
    y += boxH + 6;

    // ── Footer on every page ──────────────────────────────────────────────
    const totalPages = doc.getNumberOfPages();
    for (let p = 1; p <= totalPages; p++) {
      doc.setPage(p);
      const fy = pageH - 10;
      doc.setDrawColor(220, 210, 200);
      doc.setLineWidth(0.3);
      doc.line(margin, fy - 4, pageW - margin, fy - 4);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(180, 160, 150);
      doc.text(
        `Shakisha - Gender Data Discovery Platform  |  GDRD Hackathon 2026  |  Republic of Rwanda  |  Page ${p} of ${totalPages}`,
        pageW / 2, fy, { align: "center" }
      );
    }

    doc.save(`shakisha_brief_${study.study_id}.pdf`);
  }

  function downloadTxt() {
    if (!brief || !study) return;
    const text = `ADVOCACY BRIEF
${"=".repeat(60)}
${study.title} (${study.year})
${study.organization}

POLICY CONTEXT
${brief.policy_context}

KEY FINDINGS
${brief.key_findings}

DATA GAPS
${brief.data_gaps}

RECOMMENDED ACTION
${brief.recommended_action}

CITATION
${brief.citation}
${"=".repeat(60)}
Generated by Shakisha — AI-Powered Gender Data Discovery Platform
GDRD Hackathon 2026
`;
    const blob = new Blob([text], { type: "text/plain" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href = url;
    a.download = `shakisha_brief_${study.study_id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const QUALITY_BADGE = {
    good:     { cls: "badge-good",     label: "Good quality" },
    warning:  { cls: "badge-warning",  label: "Some missing fields" },
    critical: { cls: "badge-critical", label: "Missing critical fields" },
  };

  // Filter studies for selector search
  const filteredStudies = allStudies.filter((s) =>
    !search || s.title.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div style={{ background: "var(--cream)", minHeight: "100vh" }}>
      <div className="page-wrap" style={{ maxWidth: 900 }}>
        <h1 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 32, fontWeight: 700, color: "var(--charcoal)", marginBottom: 8 }}>
          Advocacy Brief Generator
        </h1>
        <p style={{ color: "var(--muted)", fontSize: 14, marginBottom: 28 }}>
          Select a study and generate an AI-powered policy brief ready for advocacy use.
        </p>

        {/* Study selector */}
        <div style={{ background: "var(--warm-white)", border: "1px solid var(--border)", borderRadius: 12, padding: "24px", marginBottom: 24 }}>
          <div style={{ fontWeight: 700, fontSize: 15, color: "var(--charcoal)", marginBottom: 12 }}>
            Choose a study
          </div>
          <input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search study title…"
            style={{ width: "100%", padding: "8px 14px", borderRadius: 8, border: "1.5px solid var(--border)", background: "var(--cream)", fontSize: 13, marginBottom: 10, boxSizing: "border-box" }}
          />
          <select
            value={selectedId}
            onChange={(e) => setSelectedId(e.target.value)}
            size={6}
            style={{
              width: "100%",
              border: "1.5px solid var(--border)",
              borderRadius: 8,
              background: "var(--cream)",
              fontSize: 13,
              color: "var(--charcoal)",
              padding: "4px",
            }}
          >
            {filteredStudies.map((s) => (
              <option key={s.study_id} value={s.study_id}>
                {s.year ? `[${s.year}] ` : ""}{s.title}
              </option>
            ))}
          </select>
        </div>

        {/* Study metadata panel */}
        {study && (
          <div style={{ background: "var(--warm-white)", border: "1px solid var(--border)", borderRadius: 12, padding: "24px", marginBottom: 24 }}>
            <div className="study-meta-row">
              <div style={{ flex: 1 }}>
                <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 22, fontWeight: 700, color: "var(--charcoal)", marginBottom: 6 }}>
                  {study.title}
                </h2>
                <p style={{ color: "var(--muted)", fontSize: 13, marginBottom: 12 }}>
                  {[study.organization, study.year, study.geographic_coverage].filter(Boolean).join(" · ")}
                </p>
                {study.abstract && (
                  <p style={{ color: "var(--muted)", fontSize: 13, lineHeight: 1.6 }}>
                    {study.abstract.slice(0, 450)}{study.abstract.length > 450 ? "…" : ""}
                  </p>
                )}
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 10, minWidth: 150, alignItems: "flex-end" }}>
                <span className={`pill ${QUALITY_BADGE[study.quality_level]?.cls ?? "badge-warning"}`}>
                  {QUALITY_BADGE[study.quality_level]?.label ?? "Unknown"}
                </span>
                <span style={{ fontSize: 12, color: "var(--muted)" }}>{study.missing_field_count} missing fields</span>
                <span style={{ fontSize: 12, color: "var(--muted)" }}>{study.resource_count} resources</span>
                {study.url && (
                  <a href={study.url} target="_blank" rel="noopener noreferrer" className="btn-icon" style={{ fontSize: 12 }}>
                    View source ↗
                  </a>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Quality warning */}
        {study?.quality_level === "critical" && (
          <div style={{ background: "#FCE8E8", border: "1px solid #E8A0A0", borderRadius: 8, padding: "12px 16px", fontSize: 13, color: "var(--coral-dark)", marginBottom: 20 }}>
            <strong>Data quality warning:</strong> This study has critical missing fields. Review all caveats carefully before citing in advocacy materials.
          </div>
        )}

        {/* Generate button */}
        <div style={{ marginBottom: 28 }}>
          <button
            className="btn-primary"
            style={{ fontSize: 16, padding: "14px 32px" }}
            disabled={!selectedId || generating}
            onClick={generate}
          >
            {generating ? "Generating brief…" : "Generate Advocacy Brief"}
          </button>
          {generating && (
            <p style={{ color: "var(--muted)", fontSize: 13, marginTop: 8 }}>
              Calling Claude AI — usually takes 5–15 seconds…
            </p>
          )}
          {error && (
            <p style={{ color: "var(--coral)", fontSize: 13, marginTop: 8 }}>
              {error}
            </p>
          )}
        </div>

        {/* Brief output */}
        {brief && study && (
          <div className="animate-fade-in">
            <div
              style={{
                background: "var(--warm-white)",
                border: "1px solid var(--border)",
                borderLeft: "4px solid var(--coral)",
                borderRadius: 12,
                marginBottom: 20,
              }}
            >
              <div className="brief-card-pad">
              <div className="brief-header-row">
                <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 24, fontWeight: 700, color: "var(--charcoal)" }}>
                  Advocacy Brief
                </h2>
                <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                  <button
                    className="btn-ghost"
                    onClick={copyToClipboard}
                    style={{ fontSize: 13 }}
                  >
                    {copied ? "Copied ✓" : "Copy text"}
                  </button>
                  <button
                    className="btn-ghost"
                    onClick={downloadTxt}
                    style={{ fontSize: 13 }}
                  >
                    Download .txt
                  </button>
                  <button
                    className="btn-primary"
                    onClick={downloadPdf}
                    style={{ fontSize: 13 }}
                  >
                    Download PDF ↓
                  </button>
                </div>
              </div>

              <div className="grid-2col" style={{ gap: 28 }}>
                <div>
                  <h3 style={{ fontWeight: 700, fontSize: 14, color: "var(--coral)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10 }}>
                    Policy Context
                  </h3>
                  <p style={{ color: "var(--charcoal)", fontSize: 14, lineHeight: 1.7 }}>
                    {brief.policy_context}
                  </p>
                </div>

                <div>
                  <h3 style={{ fontWeight: 700, fontSize: 14, color: "var(--coral)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10 }}>
                    Data Gaps
                  </h3>
                  <p style={{ color: "var(--charcoal)", fontSize: 14, lineHeight: 1.7 }}>
                    {brief.data_gaps}
                  </p>
                </div>
              </div>

              <div style={{ marginTop: 24 }}>
                <h3 style={{ fontWeight: 700, fontSize: 14, color: "var(--coral)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10 }}>
                  Key Findings
                </h3>
                <div style={{ color: "var(--charcoal)", fontSize: 14, lineHeight: 2 }}>
                  {brief.key_findings.split("\n").filter(Boolean).map((line, i) => (
                    <div key={i} style={{ display: "flex", gap: 10, marginBottom: 4 }}>
                      <span style={{ color: "var(--coral)", fontWeight: 700, flexShrink: 0 }}>•</span>
                      <span>{line.replace(/^[•\-]\s*/, "")}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div
                style={{
                  marginTop: 24,
                  background: "rgba(32,96,61,0.07)",
                  border: "1px solid var(--rw-green-light)",
                  borderRadius: 8,
                  padding: "16px 20px",
                }}
              >
                <h3 style={{ fontWeight: 700, fontSize: 14, color: "var(--rw-green)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 }}>
                  Recommended Action
                </h3>
                <p style={{ color: "var(--charcoal)", fontSize: 14, lineHeight: 1.7 }}>
                  {brief.recommended_action}
                </p>
              </div>

              <div style={{ marginTop: 24 }}>
                <h3 style={{ fontWeight: 700, fontSize: 14, color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 }}>
                  Citation
                </h3>
                <div className="citation-block">{brief.citation}</div>
              </div>

              {/* Quality caveat in brief */}
              {study.quality_level !== "good" && (
                <div style={{ marginTop: 20, background: "#FEF3B0", border: "1px solid var(--rw-yellow)", borderRadius: 8, padding: "12px 16px", fontSize: 12, color: "#92620A" }}>
                  <strong>Quality note:</strong> This study has {study.missing_field_count} missing metadata field{study.missing_field_count !== 1 ? "s" : ""}. Cross-check cited figures with the original source before formal advocacy use.
                </div>
              )}
              </div>{/* end brief-card-pad */}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default function BriefPage() {
  return (
    <Suspense fallback={<div style={{ padding: 48, color: "var(--muted)" }}>Loading…</div>}>
      <BriefContent />
    </Suspense>
  );
}
