from __future__ import annotations

import io
import os

import streamlit as st
from dotenv import load_dotenv

load_dotenv(override=True)

from src.ai import advocacy_brief
from src.brief_store import delete_brief, list_briefs, load_brief, save_brief
from src.loaders import load_all_data
from src.quality_badges import parse_quality_flags, quality_level


def _safe(text: str) -> str:
    """Sanitize text to latin-1 so fpdf core fonts can render it."""
    replacements = {
        "\u2022": "-", "\u2013": "-", "\u2014": "-",
        "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
        "\u2026": "...",
    }
    for char, sub in replacements.items():
        text = text.replace(char, sub)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _build_pdf(brief: dict, title: str, year: str, org: str, quality_note: str) -> bytes:
    from fpdf import FPDF
    from fpdf.enums import XPos, YPos

    LM, RM, TM = 20, 20, 20
    pdf = FPDF(format="A4")
    pdf.set_margins(LM, TM, RM)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    W = pdf.w - LM - RM  # effective content width

    # Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(W, 10, "ADVOCACY BRIEF", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(W, 7, _safe(f"{title} ({year})"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.multi_cell(W, 7, _safe(org), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)
    pdf.line(LM, pdf.get_y(), LM + W, pdf.get_y())
    pdf.ln(6)

    sections = [
        ("Policy Context", brief.get("policy_context", "")),
        ("Key Findings", brief.get("key_findings", "")),
        ("Data Gaps", brief.get("data_gaps", "")),
        ("Recommended Action", brief.get("recommended_action", "")),
    ]

    for heading, body in sections:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(W, 8, heading, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 10)
        for line in body.split("\n"):
            line = line.strip()
            if line:
                pdf.multi_cell(W, 6, _safe(line), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(3)

    # Citation box
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(W, 8, "Citation", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Courier", "", 9)
    pdf.set_fill_color(245, 245, 245)
    pdf.multi_cell(W, 6, _safe(brief.get("citation", "")), fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # Quality note
    if quality_note:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(180, 60, 0)
        pdf.multi_cell(W, 5, _safe(quality_note), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)

    # Footer
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(W, 6, "Generated by Shakisha - AI-Powered Gender Data Discovery | GRB Hackathon 2026", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())

AI_AVAILABLE = bool(os.getenv("ANTHROPIC_API_KEY", "").strip())

studies, resources, quality = load_all_data()

st.title("Advocacy Brief Generator")
st.caption("Select a study to generate an AI-powered policy brief ready for advocacy use.")

if not AI_AVAILABLE:
    st.warning(
        "AI features require an Anthropic API key. "
        "Set `ANTHROPIC_API_KEY` in your environment to enable brief generation."
    )

# ── Study selector ─────────────────────────────────────────────────────────────
# Pre-select from session_state if user clicked "Generate brief →" on Discovery page
pre_selected = st.session_state.get("selected_study_id", None)

study_options = studies[["study_id", "title"]].copy()
id_to_title = dict(zip(study_options["study_id"], study_options["title"]))

if pre_selected and pre_selected in id_to_title:
    default_index = list(id_to_title.keys()).index(pre_selected)
else:
    default_index = 0

selected_id = st.selectbox(
    "Choose a study",
    options=list(id_to_title.keys()),
    format_func=lambda sid: id_to_title.get(sid, str(sid)),
    index=default_index,
)

# Clear session state after use
if "selected_study_id" in st.session_state:
    del st.session_state["selected_study_id"]

# ── Load selected study data ───────────────────────────────────────────────────
study_row = studies[studies["study_id"] == selected_id].iloc[0].to_dict()
study_resources = resources[resources["study_id"] == selected_id].to_dict("records")
quality_row = quality[quality["study_id"] == selected_id]

# ── Study metadata panel ───────────────────────────────────────────────────────
st.divider()
col_meta, col_quality = st.columns([3, 1])

with col_meta:
    st.subheader(str(study_row.get("title", "Untitled")))
    st.caption(
        f"{study_row.get('organization', '—')} · "
        f"{study_row.get('year', '—')} · "
        f"Coverage: {study_row.get('geographic_coverage', 'Rwanda')}"
    )
    abstract = str(study_row.get("abstract", ""))
    if abstract and abstract != "nan":
        with st.expander("Abstract", expanded=True):
            st.write(abstract[:600] + ("…" if len(abstract) > 600 else ""))

with col_quality:
    if not quality_row.empty:
        missing = int(quality_row.iloc[0]["missing_field_count"])
        level = quality_level(missing)
        BADGE = {"good": "🟢", "warning": "🟡", "critical": "🔴"}
        LABEL = {"good": "Good quality", "warning": "Some missing fields", "critical": "Missing critical fields"}
        st.metric("Quality", f"{BADGE[level]} {LABEL[level]}")
        st.metric("Missing fields", missing)
        flags = parse_quality_flags(str(quality_row.iloc[0].get("quality_flags", "")))
        if flags:
            st.caption("**Caveats:**")
            for f in flags:
                st.caption(f"• {f}")

    # Resources
    st.metric("Resources", len(study_resources))
    if study_resources:
        types = sorted({str(r.get("type", "")).lower() for r in study_resources if r.get("type")})
        st.caption("Types: " + ", ".join(types))

    # Source links
    def _clean_url(val) -> str:
        s = str(val or "").strip()
        return "" if s in ("nan", "None") else s

    url = _clean_url(study_row.get("url", ""))
    microdata_url = _clean_url(study_row.get("get_microdata_url", ""))
    if url:
        st.link_button("View source →", url, use_container_width=True)
    if microdata_url:
        st.link_button("Get microdata →", microdata_url, use_container_width=True)

# ── Brief generation ───────────────────────────────────────────────────────────
st.divider()

if not AI_AVAILABLE:
    st.stop()

if not quality_row.empty:
    level = quality_level(int(quality_row.iloc[0]["missing_field_count"]))
    if level == "critical":
        st.warning(
            "**Data quality warning:** This study has critical missing fields. "
            "Review all caveats carefully before citing this data in advocacy materials."
        )

if st.button("Generate Advocacy Brief", type="primary", use_container_width=False):
    with st.spinner("Generating policy brief..."):
        try:
            brief = advocacy_brief(study_row, study_resources)
            st.session_state["current_brief"] = brief
            st.session_state["brief_study_id"] = selected_id
            save_brief(
                study_id=selected_id,
                title=str(study_row.get("title", "Untitled")),
                org=str(study_row.get("organization", "")),
                year=str(study_row.get("year", "")),
                brief=brief,
            )
        except Exception as e:
            st.error(f"Brief generation failed: {e}")
            st.stop()

# ── Render brief ───────────────────────────────────────────────────────────────
brief = st.session_state.get("current_brief")
brief_study = st.session_state.get("brief_study_id")

if brief and brief_study == selected_id:
    st.subheader("Advocacy Brief")

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("#### Policy Context")
        st.write(brief.get("policy_context", "—"))

        st.markdown("#### Key Findings")
        findings = brief.get("key_findings", "")
        st.markdown(findings)

    with col2:
        st.markdown("#### Data Gaps")
        st.write(brief.get("data_gaps", "—"))

        st.markdown("#### Recommended Action")
        st.info(brief.get("recommended_action", "—"))

    st.divider()
    st.markdown("#### Citation")
    citation = brief.get("citation", "")
    st.code(citation, language=None)

    # Quality caveat banner — shown inline in the brief for critical studies
    if not quality_row.empty:
        _level = quality_level(int(quality_row.iloc[0]["missing_field_count"]))
        if _level == "critical":
            st.warning(
                "**Quality caveat (embedded in this brief):** This study has 3 or more missing metadata fields. "
                "Verify original source data before citing in formal advocacy or policy documents."
            )
        elif _level == "warning":
            st.info(
                "**Quality note:** This study has 1–2 missing metadata fields. "
                "Cross-check cited figures with the original source."
            )

    # ── Export ─────────────────────────────────────────────────────────────────
    title = str(study_row.get("title", "study"))
    year = str(study_row.get("year", ""))
    org = str(study_row.get("organization", ""))

    _q_level = quality_level(int(quality_row.iloc[0]["missing_field_count"])) if not quality_row.empty else "good"
    _quality_note = ""
    if _q_level == "critical":
        _quality_note = "QUALITY CAVEAT: This study has 3+ missing metadata fields. Verify source data before formal citation."
    elif _q_level == "warning":
        _quality_note = "QUALITY NOTE: This study has 1–2 missing metadata fields. Cross-check figures with the original source."

    brief_text = f"""ADVOCACY BRIEF
{'=' * 60}
{title} ({year})
{org}

POLICY CONTEXT
{brief.get('policy_context', '')}

KEY FINDINGS
{brief.get('key_findings', '')}

DATA GAPS
{brief.get('data_gaps', '')}

RECOMMENDED ACTION
{brief.get('recommended_action', '')}

CITATION
{brief.get('citation', '')}
{chr(10) + _quality_note if _quality_note else ''}
{'=' * 60}
Generated by Shakisha — AI-Powered Gender Data Discovery Platform
GRB Hackathon 2026
"""

    pdf_bytes = _build_pdf(brief, title, year, org, _quality_note)

    dl_col1, dl_col2 = st.columns(2)
    with dl_col1:
        st.download_button(
            label="Download as PDF",
            data=pdf_bytes,
            file_name=f"shakisha_brief_{selected_id}.pdf",
            mime="application/pdf",
            use_container_width=True,
        )
    with dl_col2:
        st.download_button(
            label="Download as .txt",
            data=brief_text,
            file_name=f"shakisha_brief_{selected_id}.txt",
            mime="text/plain",
            use_container_width=True,
        )

# ── Brief History ───────────────────────────────────────────────────────────────
st.divider()
saved = list_briefs()
with st.expander(f"Brief history ({len(saved)} saved)", expanded=len(saved) > 0 and not brief):
    if not saved:
        st.caption("No briefs saved yet. Generate one above to start your history.")
    else:
        for record in saved:
            rec_title = record.get("title", "Untitled")
            rec_org = record.get("organization", "")
            rec_year = record.get("year", "")
            rec_saved = record.get("saved_at", "")[:16].replace("T", " ")
            rec_file = record["_filename"]

            with st.container(border=True):
                h_col, d_col = st.columns([5, 1])
                with h_col:
                    st.markdown(f"**{rec_title}**")
                    st.caption(f"{rec_org} · {rec_year} · Saved {rec_saved}")
                with d_col:
                    if st.button("Delete", key=f"del_{rec_file}", type="secondary"):
                        delete_brief(rec_file)
                        st.rerun()

                # Reload brief into current session
                if st.button("Load this brief", key=f"load_{rec_file}", use_container_width=True):
                    loaded = load_brief(rec_file)
                    if loaded:
                        study_id_to_load = loaded.get("study_id")
                        st.session_state["current_brief"] = loaded["brief"]
                        st.session_state["brief_study_id"] = study_id_to_load
                        # Switch the study selector to match the loaded brief
                        st.session_state["selected_study_id"] = study_id_to_load
                    st.rerun()

                # Re-download buttons from stored data
                stored_brief = record.get("brief", {})
                _stored_title = record.get("title", "study")
                _stored_year = record.get("year", "")
                _stored_org = record.get("organization", "")
                _stored_txt = f"""ADVOCACY BRIEF\n{'=' * 60}\n{_stored_title} ({_stored_year})\n{_stored_org}\n\nPOLICY CONTEXT\n{stored_brief.get('policy_context', '')}\n\nKEY FINDINGS\n{stored_brief.get('key_findings', '')}\n\nDATA GAPS\n{stored_brief.get('data_gaps', '')}\n\nRECOMMENDED ACTION\n{stored_brief.get('recommended_action', '')}\n\nCITATION\n{stored_brief.get('citation', '')}\n{'=' * 60}\nGenerated by Shakisha — GRB Hackathon 2026\n"""
                try:
                    _stored_pdf = _build_pdf(stored_brief, _stored_title, _stored_year, _stored_org, "")
                    dl1, dl2 = st.columns(2)
                    with dl1:
                        st.download_button("PDF", _stored_pdf, file_name=f"shakisha_{rec_file.replace('.json','.pdf')}", mime="application/pdf", key=f"pdf_{rec_file}", use_container_width=True)
                    with dl2:
                        st.download_button("TXT", _stored_txt, file_name=f"shakisha_{rec_file.replace('.json','.txt')}", mime="text/plain", key=f"txt_{rec_file}", use_container_width=True)
                except Exception:
                    st.download_button("TXT", _stored_txt, file_name=f"shakisha_{rec_file.replace('.json','.txt')}", mime="text/plain", key=f"txt_{rec_file}", use_container_width=True)
